### ISSUE TITLE
Error loading packge 

### ISSUE THREAD

**Issue by ngBroken** [durtal/betfaiR#11]
Nice work building this package, it looks really interesting and I'm keen to take a look.
I'm having trouble installing the package. after running 

`devtools::install_github("durtal/betfaiR")`

`\* installing _source_ package 'betfaiR' ...
*\* R
*\* tests
*\* preparing package for lazy loading
*\* help
**\* installing help indices
*\* building package indices
*\* testing if installed package can be loaded
**\* arch - i386
Error in namespaceExport(ns, exports) : undefined exports: collect_data
Error: loading failed
Execution halted
**\* arch - x64
Error in namespaceExport(ns, exports) : undefined exports: collect_data
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
- removing 'C:/Users/xx/Documents/R/win-library/3.2/betfaiR'
  Error: Command failed (1)`

Any thoughts?

**Comment by durtal** [comment]
Hi, looks like I exported a function (`collect_data`) which I didn't wish to export just yet.

Hopefully [this commit](https://github.com/durtal/betfaiR/commit/cb5eb8723805a82152806bd70479eccb7ac789d4) addresses issue, let me know any other issues/queries/enhancements you may have.

Thanks for raising!

**Comment by ngBroken** [comment]
Yes all good now!!
Thanks, I'll let you know how I go..

**Comment by durtal** [comment]
Excellent, very lazy from me, sorry.

Let me know any other problems you run into, or features you'd like adding.

Thanks
