### ISSUE TITLE
Swedish jurisdiction

### ISSUE THREAD

**Issue by dahlinniclas** [durtal/betfaiR#18]
Hello! 

Just started using the package when the gambling law changed in Sweden the 1st of January. Can you please add..

"sweden" = "https://identitysso.betfair.se/api/login" 

..to the rest of the countries in the jurisdiction switch in betfair_login.R? 

Thank you for a good package!

**Comment by durtal** [comment]
hi @dahlinniclas,

Just pushed a [change to add sweden](https://github.com/durtal/betfaiR/commit/3923a25a21b907336d62f273b85823bb9bceb846), so hopefully you can login now, if you have issues then let me know. I'll leave this issue open for now. If you see things that you'd like adding/improving then please let me know and I'll see what I can do.

Best

**Comment by dahlinniclas** [comment]
Great, login is working again. 

Will let you know if I find something to add. 

Thank you!
